<?php

namespace FilmBundle\Repository;

/**
 * GenresRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GenresRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * List of genres in alphabetical order
     *
     * @return array
     */
    public function findAllGenreByOrder()
    {
        $query = $this->getEntityManager()->createQueryBuilder()
            ->select('g')
            ->from('FilmBundle:Genres', 'g')
            ->orderBy('g.name', 'ASC')
            ->getQuery();

        return $query->getResult();
    }
}
