<?php

namespace FilmBundle\Repository;

/**
 * ProductionsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductionsRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * List of productions in alphabetical order
     *
     * @return array
     */
    public function findAllProdByOrder()
    {
        $query = $this->getEntityManager()->createQueryBuilder()
            ->select('p')
            ->from('FilmBundle:Productions', 'p')
            ->orderBy('p.name', 'ASC')
            ->getQuery();

        return $query->getResult();
    }
}
